name = "event-manager-push-consumer"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "event-manager-db"
database_id = "19a07556-5f71-4bdf-b0e9-7a2de9618668"

[[queues.consumers]]
queue = "push-notifications"
max_batch_size = 5
max_retries = 3
